# -*- coding: utf-8 -*-
"""
题库：5 种语言 × 5 个难度 × 5 题，覆盖各语言主要语法与特性。
level: beginner 入门 / elementary 初级 / intermediate 中级 / advanced 高级 / expert 精通
字段: id, lang, level, title, desc, starter(可选), stdin(可选), expected, explain
"""

LEVELS = {
    "beginner": "入门",
    "elementary": "初级",
    "intermediate": "中级",
    "advanced": "高级",
    "expert": "精通",
    "practical": "实战",
}

LANG_MAP = {
    "python": {"name": "Python", "piston": "python"},
    "c": {"name": "C", "piston": "c"},
    "java": {"name": "Java", "piston": "java"},
    "rust": {"name": "Rust", "piston": "rust"},
    "cpp": {"name": "C++", "piston": "c++"},
}

QUESTIONS = [
{"id": "c-01", "lang": "c", "level": "beginner",
     "title": "printf 输出", "desc": "使用 printf 输出：Hello, World!",
     "expected": "Hello, World!", "explain": "printf 是 C 标准输出函数，字符串以 \\n 结尾。"},
{"id": "c-02", "lang": "c", "level": "beginner",
     "title": "变量与数据类型", "desc": "定义 int n = 7、double d = 3.5、char c = 'A'。输出一行：7 3.5 A",
     "expected": "7 3.5 A",
     "explain": "%d 整型、%.1f 一位小数浮点、%c 字符。"},
{"id": "c-03", "lang": "c", "level": "beginner",
     "title": "if-else 与 scanf", "desc": "读取两个整数，输出其中较大的数。\n输入示例：5 3",
     "stdin": "5 3", "expected": "5",
     "explain": "scanf(\"%d %d\") 读取输入，if-else 比较取最大值。"},
{"id": "c-04", "lang": "c", "level": "beginner",
     "title": "for 循环", "desc": "读取整数 n，输出 1 到 n 的和。\n输入示例：100",
     "stdin": "100", "expected": "5050",
     "explain": "for 循环三要素：初始化、条件、更新。"},
{"id": "c-05", "lang": "c", "level": "beginner",
     "title": "while 循环", "desc": "读取整数 n，输出 1 到 n 之间的所有偶数（空格分隔）。\n输入示例：10",
     "stdin": "10", "expected": "2 4 6 8 10",
     "explain": "while 条件循环配合取模 % 判断偶数。"},
{"id": "c-06", "lang": "c", "level": "beginner",
     "title": "printf 格式控制", "desc": "输出：十进制 255、十六进制 0xff、宽度补零 0042、两位小数 3.14（空格分隔）。",
     "expected": "255 0xff 0042 3.14",
     "explain": "%#x 带前缀十六进制，%04d 宽度补零，%.2f 小数位数。"},
{"id": "c-07", "lang": "c", "level": "beginner",
     "title": "字符与 ASCII", "desc": "char c='A'。输出 c 的 ASCII 码（整数），以及 c+32 对应的字符（小写 a）。",
     "expected": "65\na",
     "explain": "字符本质是整数，'A'=65，+32 变为小写。"},
{"id": "c-08", "lang": "c", "level": "beginner",
     "title": "逻辑运算符与短路", "desc": "a=5, b=10。依次输出 a>0 && b>0、a>10 || b==10、!(a==5) 的结果（1 或 0）。",
     "expected": "1\n1\n0",
     "explain": "&& 与、|| 或、! 非；短路求值。"},
{"id": "c-09", "lang": "c", "level": "beginner",
     "title": "条件运算符", "desc": "x=7。输出 x%2==0 ? \"even\" : \"odd\"，再输出 x>5 ? x*2 : x。",
     "expected": "odd\n14",
     "explain": "条件 ? 真值 : 假值，是表达式。"},
{"id": "c-10", "lang": "c", "level": "beginner",
     "title": "do-while 循环", "desc": "用 do-while 计算 5+4+3+2+1，输出结果。",
     "expected": "15",
     "explain": "do-while 至少执行一次循环体。"},
{"id": "c-11", "lang": "c", "level": "elementary",
     "title": "数组", "desc": "int a[5] = {1,2,3,4,5}; 逆序输出：5 4 3 2 1",
     "expected": "5 4 3 2 1",
     "explain": "数组下标从 0 开始，从 4 到 0 递减遍历。"},
{"id": "c-12", "lang": "c", "level": "elementary",
     "title": "字符串处理", "desc": "char s[] = \"hello\"; 复制到 t 后拼接 \" world\"。输出：字符串 s 的长度 和 拼接结果（空格分隔）。",
     "expected": "5 hello world",
     "explain": "strlen 求长度，strcpy 复制，strcat 拼接，需包含 string.h。"},
{"id": "c-13", "lang": "c", "level": "elementary",
     "title": "指针基础", "desc": "写 swap 函数（用指针交换两个 int 的值），交换 a=3, b=8 后输出 a 和 b。",
     "expected": "8 3",
     "explain": "指针保存变量地址，*p 解引用可修改原变量。"},
{"id": "c-14", "lang": "c", "level": "elementary",
     "title": "函数与递归", "desc": "写递归函数 fact(n) 计算 n!，输出 fact(6) 的结果。",
     "expected": "720",
     "explain": "递归：fact(n) = n * fact(n-1)，需有终止条件 n<=1。"},
{"id": "c-15", "lang": "c", "level": "elementary",
     "title": "switch 语句", "desc": "读取 1~3 的整数，输出对应英文星期：1=Monday、2=Tuesday、3=Wednesday，其他输出 Other。\n输入示例：2",
     "stdin": "2", "expected": "Tuesday",
     "explain": "switch-case 按值匹配，注意 break 防止穿透。"},
{"id": "c-16", "lang": "c", "level": "elementary",
     "title": "sizeof 与类型大小", "desc": "输出 int、double、int[10] 的 sizeof（字节数），三行。",
     "expected": "4\n8\n40",
     "explain": "sizeof 编译期求类型占用的字节数。"},
{"id": "c-17", "lang": "c", "level": "elementary",
     "title": "数组最大值与最小值", "desc": "int a[]={5,2,8,1,9}，找出最大值与最小值，输出。",
     "expected": "9 1",
     "explain": "遍历数组比较更新极值。"},
{"id": "c-18", "lang": "c", "level": "elementary",
     "title": "strcmp 字符串比较", "desc": "输出 strcmp(\"abc\",\"abd\")、strcmp(\"abc\",\"abc\")、strcmp(\"zz\",\"aa\")（三行）。",
     "expected": "-1\n0\n1",
     "explain": "strcmp 按字典序返回负数/0/正数。"},
{"id": "c-19", "lang": "c", "level": "elementary",
     "title": "多参数函数", "desc": "写 max3(a,b,c) 返回最大者，输出 max3(3,9,6)。",
     "expected": "9",
     "explain": "函数可接收多个参数，返回单个值。"},
{"id": "c-20", "lang": "c", "level": "elementary",
     "title": "continue 与 break", "desc": "for i=1..10：i 能被 3 整除则 continue，i>7 则 break，否则输出 i（空格分隔）。",
     "expected": "1 2 4 5 7",
     "explain": "continue 跳过本次，break 跳出整个循环。"},
{"id": "c-21", "lang": "c", "level": "intermediate",
     "title": "二维数组", "desc": "int m[2][3] = {{1,2,3},{4,5,6}}; 输出该矩阵转置（3 行 2 列），每行两个数空格分隔。",
     "expected": "1 4\n2 5\n3 6",
     "explain": "二维数组按行存储，转置即交换行列下标。"},
{"id": "c-22", "lang": "c", "level": "intermediate",
     "title": "结构体 struct", "desc": "定义 Student 结构体（name[20]、score）。创建 3 名学生，输出分数最高者的名字和分数。",
     "expected": "Bob 92",
     "explain": "struct 聚合不同类型；结构体变量用 . 访问成员。"},
{"id": "c-23", "lang": "c", "level": "intermediate",
     "title": "动态内存 malloc", "desc": "用 malloc 为 5 个整数分配内存，填入 1~5，求累加和并输出，最后 free。",
     "expected": "15",
     "explain": "malloc 分配堆内存，free 释放；包含 stdlib.h。"},
{"id": "c-24", "lang": "c", "level": "intermediate",
     "title": "位运算", "desc": "统计整数 13（二进制 1101）中二进制 1 的个数，输出结果。",
     "expected": "3",
     "explain": "n &= (n-1) 每次消除最低位的 1，计数循环。"},
{"id": "c-25", "lang": "c", "level": "intermediate",
     "title": "函数指针数组", "desc": "定义 add/sub/mul/div 四个函数（int,int），放入函数指针数组。对 10 和 5 依次调用并输出四个结果（空格分隔）。",
     "expected": "15 5 50 2",
     "explain": "函数名即函数指针，数组可存储并统一调用。"},
{"id": "c-26", "lang": "c", "level": "intermediate",
     "title": "指针运算遍历数组", "desc": "int a[]={10,20,30,40}，用 *(p+i) 输出全部元素；再将指针 +2 解引用输出。",
     "expected": "10 20 30 40\n30",
     "explain": "指针加减整数按元素大小移动；解引用取值。"},
{"id": "c-27", "lang": "c", "level": "intermediate",
     "title": "结构体数组冒泡排序", "desc": "Point {x,y} 数组 {{4,7},{1,9},{3,2}} 按 x 升序冒泡排序，每行输出 x y。",
     "expected": "1 9\n3 2\n4 7",
     "explain": "结构体数组可用整体交换排序。"},
{"id": "c-28", "lang": "c", "level": "intermediate",
     "title": "递归遍历字符串", "desc": "写递归 count(s)：s 为空返回 0，否则 1+count(s+1)。输出 count(\"hello\")。",
     "expected": "5",
     "explain": "指针后移实现递归遍历字符串。"},
{"id": "c-29", "lang": "c", "level": "intermediate",
     "title": "二维数组指针", "desc": "int m[2][3]={{1,2,3},{4,5,6}}。用 row[1][1] 和 *(*(m+1)+2) 输出两个元素。",
     "expected": "5\n6",
     "explain": "二维数组名退化为一维数组指针；双层解引用取元素。"},
{"id": "c-30", "lang": "c", "level": "intermediate",
     "title": "atoi 字符串转整数", "desc": "输出 atoi(\"123\")+1 和 atoi(\"-7\")*2。",
     "expected": "124\n-14",
     "explain": "stdlib 的 atoi 把字符串解析为 int。"},
{"id": "c-31", "lang": "c", "level": "advanced",
     "title": "链表", "desc": "用头插法建立链表：依次插入 1,2,3（头插），然后顺序遍历输出。",
     "expected": "3 2 1",
     "explain": "链表节点含数据与 next 指针；头插法新节点成为头结点。"},
{"id": "c-32", "lang": "c", "level": "advanced",
     "title": "递归：汉诺塔", "desc": "写 hanoi(n, 'A', 'C', 'B') 递归函数，输出把 3 个盘子从 A 移到 C 所需的移动次数。",
     "expected": "7",
     "explain": "汉诺塔次数 f(n) = 2*f(n-1)+1；3 个盘子需 7 步。"},
{"id": "c-33", "lang": "c", "level": "advanced",
     "title": "strtok 字符串分割", "desc": "char s[] = \"apple,banana,orange\"; 用 strtok 按逗号分割，每行输出一个单词。",
     "expected": "apple\nbanana\norange",
     "explain": "strtok 原地修改字符串，以 NULL 继续分割，需循环调用。"},
{"id": "c-34", "lang": "c", "level": "advanced",
     "title": "文件操作", "desc": "用 fopen 以写模式创建 data.txt 写入 \"Hello File\"，再以读模式打开读出并输出（关闭后重开）。",
     "expected": "Hello File",
     "explain": "fopen/fprintf/fscanf/fclose 完成文件读写，读写后应关闭。"},
{"id": "c-35", "lang": "c", "level": "advanced",
     "title": "指针数组与字符串排序", "desc": "char *names[] = {\"pear\",\"apple\",\"kiwi\"}; 用冒泡排序按字典序排序后每行输出一个。",
     "expected": "apple\nkiwi\npear",
     "explain": "指针数组存字符串常量；strcmp 比较字典序。"},
{"id": "c-36", "lang": "c", "level": "advanced",
     "title": "链表删除节点", "desc": "建立 1→2→3→4 链表，删除值为 3 的节点后顺序遍历输出。",
     "expected": "1 2 4",
     "explain": "删除节点需把前驱的 next 指向后继。"},
{"id": "c-37", "lang": "c", "level": "advanced",
     "title": "栈（数组实现）", "desc": "用数组实现 push/pop。压入 1,2,3，弹两次，压入 9，再弹一次。输出三次 pop 的结果（每行）。",
     "expected": "3\n2\n9",
     "explain": "栈后进先出，top 指针维护栈顶。"},
{"id": "c-38", "lang": "c", "level": "advanced",
     "title": "二分查找", "desc": "在升序数组 {1,3,5,7,9} 中查找 7 返回下标，查找 4 返回 -1。输出两个结果。",
     "expected": "3\n-1",
     "explain": "二分查找每次折半，需数组有序。"},
{"id": "c-39", "lang": "c", "level": "advanced",
     "title": "qsort 排序字符串数组", "desc": "指针数组 {\"pear\",\"apple\",\"kiwi\",\"grape\"} 用 qsort 按字典序排序，每行输出一个。",
     "expected": "apple\ngrape\nkiwi\npear",
     "explain": "比较函数用 strcmp，注意比较的是指针的地址。"},
{"id": "c-40", "lang": "c", "level": "advanced",
     "title": "递归最大公约数", "desc": "写 gcd(a,b)（辗转相除法），输出 gcd(48,36) 与 gcd(17,5)。",
     "expected": "12\n1",
     "explain": "gcd(a,b)=gcd(b,a%b)，b 为 0 时返回 a。"},
{"id": "c-41", "lang": "c", "level": "expert",
     "title": "宏与预处理", "desc": "定义 MAX(a,b) 宏、STR(x) 字符串化宏、CAT(a,b) 连接宏。\n输出 MAX(3,7) 和 STR(hi)；再用 CAT 连接成变量名 myvar 并赋 42 输出。",
     "expected": "7 hi\n42",
     "explain": "#define 在编译前文本替换；# 字符串化、## 拼接。"},
{"id": "c-42", "lang": "c", "level": "expert",
     "title": "位域与联合体", "desc": "定义位域结构体：unsigned a:1, b:3, c:2，赋 {1,5,2} 输出三值与 sizeof。\n再定义联合体 { int i; unsigned char bytes[4]; } 赋 0x01020304，输出 bytes[0]。",
     "expected": "1 5 2 4\n4",
     "explain": "位域按位分配内存（1+3+2 位对齐到 4 字节）；union 成员共享内存，小端低字节在前。"},
{"id": "c-43", "lang": "c", "level": "expert",
     "title": "qsort 排序结构体", "desc": "定义 Point 结构体 {int x, y}，数组 {{4,7},{1,9},{3,2}}，用 qsort 按 x 升序排序，输出每行 x y。",
     "expected": "1 9\n3 2\n4 7",
     "explain": "qsort(数组, 个数, 大小, 比较函数)；比较函数返回差的正负号。"},
{"id": "c-44", "lang": "c", "level": "expert",
     "title": "多级指针", "desc": "int arr[] = {10,20,30}; 定义 int *p = arr 与 int **pp = &p。通过 pp 输出 *pp[0] 和 *pp[1]（即前两个元素）。",
     "expected": "10 20",
     "explain": "二级指针指向指针的地址；*pp 得到指针，(*pp)[i] 取元素。"},
{"id": "c-45", "lang": "c", "level": "expert",
     "title": "综合：动态二维数组", "desc": "用 malloc 动态创建 3 行 3 列二维数组，填入 a[i][j] = i*3+j+1，输出第 3 行的和，最后释放。",
     "expected": "24",
     "explain": "先分配行指针数组，再为每行分配空间；7+8+9=24。"},
{"id": "c-46", "lang": "c", "level": "expert",
     "title": "可变参数 va_list", "desc": "写 sum(count, ...) 用 va_list 累加。输出 sum(4, 1,2,3,4)。",
     "expected": "10",
     "explain": "stdarg.h 的 va_start/va_arg/va_end 处理可变参数。"},
{"id": "c-47", "lang": "c", "level": "expert",
     "title": "回调函数", "desc": "apply(a,b,f) 把 f 应用到 a、b。分别传 add 与 mul，输出 apply(3,4,add) 与 apply(3,4,mul)。",
     "expected": "7 12",
     "explain": "函数指针作参数实现回调，代码复用。"},
{"id": "c-48", "lang": "c", "level": "expert",
     "title": "位掩码操作", "desc": "n=0b1011(11)。输出 n&0b111、n|0b0100、n^0b1111 的结果（三行）。",
     "expected": "3\n15\n4",
     "explain": "& 按位与、| 按位或、^ 异或；掩码提取或设置位。"},
{"id": "c-49", "lang": "c", "level": "expert",
     "title": "memcpy 与 memset", "desc": "把 src=\"hello\" 复制到清零的 dst 并输出；把 int 数组 {1,2,3} 清零后输出三个元素。",
     "expected": "hello\n0 0 0",
     "explain": "memcpy 复制内存，memset 按字节填充。"},
{"id": "c-50", "lang": "c", "level": "expert",
     "title": "typedef 函数指针类型", "desc": "typedef int (*op)(int,int)。数组 ops[2]={add,sub}，输出 ops[0](10,4) 与 ops[1](10,4)。",
     "expected": "14 6",
     "explain": "typedef 给函数指针起别名，便于声明数组。"},
{"id": "cpp-01", "lang": "cpp", "level": "beginner",
     "title": "cout 输出", "desc": "使用 cout 输出：Hello, World!",
     "expected": "Hello, World!", "explain": "std::cout << 输出；需要 #include <iostream>。"},
{"id": "cpp-02", "lang": "cpp", "level": "beginner",
     "title": "变量与运算", "desc": "int n = 3 + 4 * 2; double d = 10.0 / 4; 输出：n 和 d（一位小数，空格分隔）。",
     "expected": "11 2.5",
     "explain": "运算符优先级：先乘除后加减；10.0/4 浮点除法。"},
{"id": "cpp-03", "lang": "cpp", "level": "beginner",
     "title": "if-else 与 cin", "desc": "读取一个分数（整数）。90 及以上输出 A，60 及以上输出 B，否则输出 C。\n输入示例：85",
     "stdin": "85", "expected": "B",
     "explain": "std::cin >> 读取输入；if-else if-else 分支。"},
{"id": "cpp-04", "lang": "cpp", "level": "beginner",
     "title": "for 循环", "desc": "读取整数 n，输出 1 到 n 的和。\n输入示例：100",
     "stdin": "100", "expected": "5050",
     "explain": "for(int i=1;i<=n;i++) 累加。"},
{"id": "cpp-05", "lang": "cpp", "level": "beginner",
     "title": "while 循环", "desc": "用 while 倒序输出：3 2 1（空格分隔）。",
     "expected": "3 2 1",
     "explain": "while(条件) 循环，递减计数器。"},
{"id": "cpp-06", "lang": "cpp", "level": "beginner",
     "title": "setw 与进制格式化", "desc": "setw(5) 输出 42（右对齐补空格）、hex 输出 255、fixed 两位小数输出 3.14159。三行。",
     "expected": "   42\nff\n3.14",
     "explain": "<iomanip> 的 setw/setprecision 控制格式。"},
{"id": "cpp-07", "lang": "cpp", "level": "beginner",
     "title": "字符与 ASCII", "desc": "c='A'：输出 ASCII 码 65 与 c+32 的字符。",
     "expected": "65\na",
     "explain": "char 可转 int 求 ASCII，+32 转小写。"},
{"id": "cpp-08", "lang": "cpp", "level": "beginner",
     "title": "逻辑运算符", "desc": "a=5, b=10。输出 a>0&&b>0、a>10||b==10、!(a==5)（1/0）。",
     "expected": "1\n1\n0",
     "explain": "&&、||、! 逻辑运算，结果 1/0。"},
{"id": "cpp-09", "lang": "cpp", "level": "beginner",
     "title": "三元运算符", "desc": "x=7。输出 x%2==0?\"even\":\"odd\" 与 x>5?x*2:x。",
     "expected": "odd\n14",
     "explain": "?: 条件表达式。"},
{"id": "cpp-10", "lang": "cpp", "level": "beginner",
     "title": "do-while 循环", "desc": "用 do-while 计算 5+4+3+2+1。",
     "expected": "15",
     "explain": "do-while 至少执行一次。"},
{"id": "cpp-11", "lang": "cpp", "level": "elementary",
     "title": "数组与 std::string", "desc": "int a[] = {1,2,3,4,5}; 输出逆序数组。std::string s = \"cpp\"; 输出 s 与长度。\n两行输出。",
     "expected": "5 4 3 2 1\ncpp 3",
     "explain": "C 数组遍历；std::string 是类，length() 求长。"},
{"id": "cpp-12", "lang": "cpp", "level": "elementary",
     "title": "vector 容器", "desc": "vector<int> v; 依次 push_back 1..5，输出：大小、第 3 个元素、所有元素（空格分隔，三行）。",
     "expected": "5\n3\n1 2 3 4 5",
     "explain": "std::vector 动态数组，push_back 追加，[i] 下标访问。"},
{"id": "cpp-13", "lang": "cpp", "level": "elementary",
     "title": "函数与引用", "desc": "写 swap(int& a, int& b) 用引用交换。交换 x=3, y=8 后输出 x 和 y。",
     "expected": "8 3",
     "explain": "引用 & 是别名，函数内修改直接作用于实参。"},
{"id": "cpp-14", "lang": "cpp", "level": "elementary",
     "title": "switch 语句", "desc": "读取 1~3 的整数，输出对应英文星期：1=Monday、2=Tuesday、3=Wednesday，其他输出 Other。\n输入示例：2",
     "stdin": "2", "expected": "Tuesday",
     "explain": "switch-case 匹配，break 跳出。"},
{"id": "cpp-15", "lang": "cpp", "level": "elementary",
     "title": "循环嵌套", "desc": "用嵌套 for 输出 3 行：第 i 行输出 i 个 #（i=1..3）。",
     "expected": "#\n##\n###",
     "explain": "外层控制行，内层控制列。"},
{"id": "cpp-16", "lang": "cpp", "level": "elementary",
     "title": "二维数组", "desc": "int m[2][3]={{1,2,3},{4,5,6}}：输出元素总和与 m[1][2]。",
     "expected": "21\n6",
     "explain": "二维数组按行连续存储。"},
{"id": "cpp-17", "lang": "cpp", "level": "elementary",
     "title": "string 查找与截取", "desc": "s=\"hello world\"：输出 find(\"world\")、substr(0,5)、find('o')。",
     "expected": "6\nhello\n4",
     "explain": "find 返回下标，substr 截取子串。"},
{"id": "cpp-18", "lang": "cpp", "level": "elementary",
     "title": "范围 for 循环", "desc": "int a[]={1,2,3,4,5} 用 for(int x : a) 求和输出。",
     "expected": "15",
     "explain": "范围 for 自动遍历容器元素。"},
{"id": "cpp-19", "lang": "cpp", "level": "elementary",
     "title": "默认参数", "desc": "power(base, exp=2) 返回幂。输出 power(5) 与 power(2,5)。",
     "expected": "25\n32",
     "explain": "默认参数在调用时省略实参自动填充。"},
{"id": "cpp-20", "lang": "cpp", "level": "elementary",
     "title": "数组初始化", "desc": "int a[5]={} 全零后 a[0]=10；输出 a[0] 与 a[4]；再输出 b={1,2,3} 的长度。",
     "expected": "10 0\n3",
     "explain": "{} 全零初始化；sizeof 求数组字节数。"},
{"id": "cpp-21", "lang": "cpp", "level": "intermediate",
     "title": "类与对象", "desc": "定义 Point 类（x、y 私有成员，构造器，distance 方法）。输出 (0,0) 到 (3,4) 距离取整。",
     "expected": "5",
     "explain": "class 封装数据与方法；构造器初始化成员；private 默认私有。"},
{"id": "cpp-22", "lang": "cpp", "level": "intermediate",
     "title": "构造与析构顺序", "desc": "类 A：构造输出 A()，析构输出 ~A()。创建两个对象 a1、a2 后结束，观察输出顺序（析构逆序）。",
     "expected": "A()\nA()\n~A()\n~A()",
     "explain": "构造按声明顺序，析构按相反顺序；栈上对象作用域结束自动析构。"},
{"id": "cpp-23", "lang": "cpp", "level": "intermediate",
     "title": "运算符重载", "desc": "定义 Complex 类（re、im），重载 + 运算符。计算 (1+2i) + (3+4i)，输出 4+6i 格式。",
     "expected": "4+6i",
     "explain": "operator+ 成员函数重载；返回新对象。"},
{"id": "cpp-24", "lang": "cpp", "level": "intermediate",
     "title": "继承", "desc": "基类 Animal（名字、speak() 返回 \"...\"），派生类 Dog 重写 speak 返回 \"Woof\"。创建 Dog 对象调用其 speak 输出。",
     "expected": "Woof",
     "explain": "public 继承；非虚方法按静态类型解析（指针调用虚方法见精通题）。"},
{"id": "cpp-25", "lang": "cpp", "level": "intermediate",
     "title": "函数重载与默认参数", "desc": "定义 add(int a, int b) 与 add(int a, int b, int c)，以及含默认参数 area(double r, double pi = 3.14)。\n依次输出 add(2,3)、add(2,3,4)、area(1.0)（两位小数）。",
     "expected": "5\n9\n3.14",
     "explain": "重载靠参数列表区分；默认参数可省略实参。"},
{"id": "cpp-26", "lang": "cpp", "level": "intermediate",
     "title": "静态成员", "desc": "Counter 类 static int count，构造时自增。创建 3 个对象输出 count。",
     "expected": "3",
     "explain": "static 成员属于类而非实例，需类外定义。"},
{"id": "cpp-27", "lang": "cpp", "level": "intermediate",
     "title": "友元函数", "desc": "Box 私有成员 v，friend 函数 get(const Box&) 可访问。输出 get(b)。",
     "expected": "42",
     "explain": "friend 声明让外部函数访问私有成员。"},
{"id": "cpp-28", "lang": "cpp", "level": "intermediate",
     "title": "拷贝构造", "desc": "Vec2 类构造打印 ctor、拷贝构造打印 copy。Vec2 b = a 后输出 b 的成员。",
     "expected": "ctor\ncopy\n1 2",
     "explain": "拷贝构造在复制对象时调用。"},
{"id": "cpp-29", "lang": "cpp", "level": "intermediate",
     "title": "枚举 enum", "desc": "enum Color { RED, GREEN=10, BLUE }，输出三个值。",
     "expected": "0\n10\n11",
     "explain": "枚举默认从 0 递增，可指定值。"},
{"id": "cpp-30", "lang": "cpp", "level": "intermediate",
     "title": "嵌套类", "desc": "Outer 内定义 Inner 类（成员 v）。创建 Outer::Inner 输出 v。",
     "expected": "7",
     "explain": "嵌套类在外层作用域内定义，用 :: 访问。"},
{"id": "cpp-31", "lang": "cpp", "level": "advanced",
     "title": "函数模板", "desc": "template <typename T> T my_max(T a, T b)。分别对整数 5,9 与字符串 \"abc\",\"abd\"（std::string）调用输出。",
     "expected": "9\nabd",
     "explain": "模板按调用实参推导类型，一次定义多类型可用。"},
{"id": "cpp-32", "lang": "cpp", "level": "advanced",
     "title": "map / set 关联容器", "desc": "map<string,int> 记录三科成绩（math:95、chinese:88、english:76）；set<int> 存储成绩。输出 map 大小、math 成绩、set 内容（空格分隔，set 升序）。",
     "expected": "3 95 76 88 95",
     "explain": "map 按键有序自动排序；set 元素唯一且有序。"},
{"id": "cpp-33", "lang": "cpp", "level": "advanced",
     "title": "sort 算法", "desc": "vector<int> {5,2,8,1,9}。升序排序输出，再降序排序输出（两行）。",
     "expected": "1 2 5 8 9\n9 8 5 2 1",
     "explain": "std::sort 默认升序；greater<int>() 或 Lambda 降序。"},
{"id": "cpp-34", "lang": "cpp", "level": "advanced",
     "title": "异常处理", "desc": "函数 divide(a, b)：b 为 0 时 throw runtime_error。捕获异常输出 Error；正常调用 divide(10,2) 输出结果。",
     "expected": "5\nError",
     "explain": "throw 抛出，try-catch 捕获；runtime_error 在 <stdexcept>。"},
{"id": "cpp-35", "lang": "cpp", "level": "advanced",
     "title": "智能指针", "desc": "shared_ptr<int> 指向值 42，依次输出值、初始 use_count、另一个 shared_ptr 也指向它后的 use_count。",
     "expected": "42\n1\n2",
     "explain": "shared_ptr 引用计数共享所有权；make_shared 创建。"},
{"id": "cpp-36", "lang": "cpp", "level": "advanced",
     "title": "find 与 count", "desc": "vector={1,2,3,2,5}：find 是否找到 3（1/0）、count 统计 2 的个数。",
     "expected": "1\n2",
     "explain": "std::find 返回迭代器，count 统计出现次数。"},
{"id": "cpp-37", "lang": "cpp", "level": "advanced",
     "title": "迭代器遍历", "desc": "vector={10,20,30}：用迭代器累加输出，再输出 rbegin()+1 的值。",
     "expected": "60\n20",
     "explain": "begin/end 正向，rbegin/rend 反向迭代器。"},
{"id": "cpp-38", "lang": "cpp", "level": "advanced",
     "title": "stringstream", "desc": "从 \"10 20 30\" 解析三个整数求和输出；再输出拼接串 \"sum=\" + 结果。",
     "expected": "60\nsum=60",
     "explain": "stringstream 把字符串当作流读写。"},
{"id": "cpp-39", "lang": "cpp", "level": "advanced",
     "title": "纯虚函数与抽象类", "desc": "Shape 含纯虚 area()，Circle 实现。基类指针调用输出面积（取整）。",
     "expected": "3",
     "explain": "纯虚函数使类抽象，不能实例化。"},
{"id": "cpp-40", "lang": "cpp", "level": "advanced",
     "title": "自定义异常类", "desc": "NegativeError 继承 runtime_error。check(-1) 抛出被捕获输出 what()；check(5) 正常输出。",
     "expected": "negative\n10",
     "explain": "自定义异常继承标准异常，catch 引用捕获。"},
{"id": "cpp-41", "lang": "cpp", "level": "expert",
     "title": "Lambda 表达式", "desc": "vector<int> {4,1,3,2}。用 Lambda 作为 sort 比较器降序排序，再用另一个捕获变量 factor 的 Lambda 映射输出每个元素乘 10。",
     "expected": "40 30 20 10",
     "explain": "[捕获]（参数）-> 返回 { 体 }；lambda 可捕获外部变量。"},
{"id": "cpp-42", "lang": "cpp", "level": "expert",
     "title": "虚函数与多态", "desc": "基类 Animal 的 speak() 声明为 virtual，Dog/Cat 重写。基类指针数组遍历调用，输出两个叫声。",
     "expected": "Woof\nMeow",
     "explain": "virtual 使调用在运行时按对象实际类型分派；override 显式重写。"},
{"id": "cpp-43", "lang": "cpp", "level": "expert",
     "title": "移动语义 std::move", "desc": "vector<string> v; 创建临时字符串 \"hello\"，用 std::move 移到 v 中；输出 v[0] 与 v 的大小。",
     "expected": "hello 1",
     "explain": "std::move 转为右值，触发移动构造避免深拷贝。"},
{"id": "cpp-44", "lang": "cpp", "level": "expert",
     "title": "STL 算法组合", "desc": "vector<int> {1,2,3,4,5}。用 accumulate 求和，用 for_each 把每个元素平方并打印（空格分隔）。两行输出。",
     "expected": "15\n1 4 9 16 25",
     "explain": "accumulate 归约求和；for_each 对每个元素施加函数。"},
{"id": "cpp-45", "lang": "cpp", "level": "expert",
     "title": "容器适配器", "desc": "使用 stack（压入 1,2,3 后依次弹出）、queue（1,2,3 依次弹出）、priority_queue（3,1,2 默认大顶堆弹出）。三行输出。",
     "expected": "3 2 1\n1 2 3\n3 2 1",
     "explain": "stack 后进先出；queue 先进先出；priority_queue 按优先级出队。"},
{"id": "cpp-46", "lang": "cpp", "level": "expert",
     "title": "unique_ptr", "desc": "make_unique<int>(42)。输出值；move 转移后输出原指针是否为空与新指针的值。",
     "expected": "42\n1 42",
     "explain": "unique_ptr 独占所有权，move 转移，不能拷贝。"},
{"id": "cpp-47", "lang": "cpp", "level": "expert",
     "title": "std::function", "desc": "std::function<int(int)> 存 Lambda 平方输出；std::plus<int>() 作二元函数输出。",
     "expected": "36\n5",
     "explain": "std::function 类型擦除的可调用对象包装。"},
{"id": "cpp-48", "lang": "cpp", "level": "expert",
     "title": "std::thread 多线程", "desc": "5 个线程各自计算 i*i（i=1..5），互斥锁保护共享 vector，join 后排序输出。",
     "expected": "1 4 9 16 25",
     "explain": "thread 启动并发，mutex 保护共享数据，join 等待。"},
{"id": "cpp-49", "lang": "cpp", "level": "expert",
     "title": "transform 与 remove_if", "desc": "vector={1..6}：transform 平方到新容器输出；remove_if 删除偶数输出剩余。",
     "expected": "1 4 9 16 25 36\n1 3 5",
     "explain": "transform 批量变换，remove_if+erase 删除条件元素。"},
{"id": "cpp-50", "lang": "cpp", "level": "expert",
     "title": "移动构造", "desc": "Buffer 有移动构造（打印 moved）。Buffer b(std::move(a)) 后输出 b 的数据与 a 的大小。",
     "expected": "ctor\nmoved\nhello size=0",
     "explain": "移动构造转移资源，源对象被置空。"},
{"id": "j-01", "lang": "java", "level": "beginner",
     "title": "Hello, World!", "desc": "输出：Hello, World!\n提示：必须使用 public class Main 与 public static void main(String[] args)。",
     "expected": "Hello, World!", "explain": "System.out.println 输出并换行；main 是程序入口。"},
{"id": "j-02", "lang": "java", "level": "beginner",
     "title": "变量与基本类型", "desc": "int n = 7; double d = 3.5; char c = 'A'; 输出一行：7 3.5 A",
     "expected": "7 3.5 A",
     "explain": "int/double/char 为基本类型，System.out.printf 可格式化输出。"},
{"id": "j-03", "lang": "java", "level": "beginner",
     "title": "if-else 与 Scanner", "desc": "读取一个分数（整数）。90 及以上输出 A，60 及以上输出 B，否则输出 C。\n输入示例：85",
     "stdin": "85", "expected": "B",
     "explain": "Scanner 读取标准输入；nextInt() 读整数。"},
{"id": "j-04", "lang": "java", "level": "beginner",
     "title": "for 循环", "desc": "读取整数 n，输出 1 到 n 的和。\n输入示例：100",
     "stdin": "100", "expected": "5050",
     "explain": "for(int i=1;i<=n;i++) 累加求和。"},
{"id": "j-05", "lang": "java", "level": "beginner",
     "title": "while / do-while 循环", "desc": "读取整数 n，用 while 输出 1 到 n 的所有偶数（空格分隔）。\n输入示例：10",
     "stdin": "10", "expected": "2 4 6 8 10",
     "explain": "while 循环配合 % 判断偶数。"},
{"id": "j-06", "lang": "java", "level": "beginner",
     "title": "printf 格式化", "desc": "输出 %d 的 42、%05d 的 42、%x 的 255（用 - 连接）。",
     "expected": "42-00042-ff",
     "explain": "printf 的 %05d 宽度补零，%x 十六进制。"},
{"id": "j-07", "lang": "java", "level": "beginner",
     "title": "逻辑运算符", "desc": "a=5, b=10, c=0。依次输出 a>0&&b>0、a>10||c>0、!(c>0)。",
     "expected": "true\nfalse\ntrue",
     "explain": "&& 与、|| 或、! 非。"},
{"id": "j-08", "lang": "java", "level": "beginner",
     "title": "字符串拼接", "desc": "输出 \"Hello\"+\" \"+\"World\"+\" \"+42，再输出 \"ha\".repeat(3)。",
     "expected": "Hello World 42\nhahaha",
     "explain": "+ 可拼接字符串与数字；repeat 重复字符串。"},
{"id": "j-09", "lang": "java", "level": "beginner",
     "title": "三元运算符", "desc": "x=7。输出 x%2==0?\"even\":\"odd\"，再输出 x>5?x*2:x。",
     "expected": "odd\n14",
     "explain": "条件 ? 值1 : 值2 表达式。"},
{"id": "j-10", "lang": "java", "level": "beginner",
     "title": "do-while 循环", "desc": "用 do-while 计算 5+4+3+2+1，输出结果。",
     "expected": "15",
     "explain": "do-while 先执行后判断。"},
{"id": "j-11", "lang": "java", "level": "elementary",
     "title": "数组", "desc": "int[] a = {1,2,3,4,5}; 逆序输出：5 4 3 2 1",
     "expected": "5 4 3 2 1",
     "explain": "数组长度 a.length，从后往前遍历。"},
{"id": "j-12", "lang": "java", "level": "elementary",
     "title": "字符串方法", "desc": "String s = \"hello world\"; 输出：大写形式 和 字符串长度（空格分隔）。",
     "expected": "HELLO WORLD 11",
     "explain": "toUpperCase() 转大写，length() 求长度。"},
{"id": "j-13", "lang": "java", "level": "elementary",
     "title": "switch 语句", "desc": "读取 1~3 的整数，输出对应英文星期：1=Monday、2=Tuesday、3=Wednesday，其他输出 Other。\n输入示例：2",
     "stdin": "2", "expected": "Tuesday",
     "explain": "switch 按值匹配，case 后必须 break。"},
{"id": "j-14", "lang": "java", "level": "elementary",
     "title": "方法重载", "desc": "定义三个 add 方法：add(int,int)、add(int,int,int)、add(double,double)。依次输出三个结果。",
     "expected": "5\n9\n5.5",
     "explain": "方法重载：同名方法不同参数列表，编译期按实参选择。"},
{"id": "j-15", "lang": "java", "level": "elementary",
     "title": "循环嵌套", "desc": "用嵌套 for 循环输出 3 行递增星号：第 i 行输出 i 个 *。",
     "expected": "*\n**\n***",
     "explain": "外层循环控制行，内层循环控制每行星号数。"},
{"id": "j-16", "lang": "java", "level": "elementary",
     "title": "二维数组", "desc": "int[][] m={{1,2,3},{4,5,6}}。输出所有元素之和，以及 m[1][2]。",
     "expected": "21\n6",
     "explain": "二维数组按行存储，可用增强 for 遍历。"},
{"id": "j-17", "lang": "java", "level": "elementary",
     "title": "String 常用方法", "desc": "s=\"Hello World\"。依次输出 charAt(0)、contains(\"World\")、indexOf(\"o\")、equals(\"hello world\")。",
     "expected": "H\ntrue\n4\nfalse",
     "explain": "charAt 取字符，contains 包含判断，indexOf 找下标，equals 区分大小写。"},
{"id": "j-18", "lang": "java", "level": "elementary",
     "title": "Arrays.sort 与二分查找", "desc": "int[]{5,2,8,1,9} 排序后输出，再用 binarySearch 找 8 输出下标。",
     "expected": "[1, 2, 5, 8, 9]\n3",
     "explain": "Arrays.sort 排序，binarySearch 需有序数组。"},
{"id": "j-19", "lang": "java", "level": "elementary",
     "title": "方法递归", "desc": "写递归 fib(n)（n<2 返回 n），输出 fib(10)。",
     "expected": "55",
     "explain": "递归方法需终止条件。"},
{"id": "j-20", "lang": "java", "level": "elementary",
     "title": "标签 break", "desc": "嵌套循环中当 i*j>3 时 break outer 跳出外层。输出执行过的 i,j 组合。",
     "expected": "1,1 1,2 1,3 2,1",
     "explain": "标签 break 可跳出多层循环。"},
{"id": "j-21", "lang": "java", "level": "intermediate",
     "title": "类与对象", "desc": "定义 Point 类（x、y 字段，构造器，distance(Point) 方法）。\n输出 p1=(0,0) 到 p2=(3,4) 的距离（转为 int）。",
     "expected": "5",
     "explain": "class 定义类型，new 创建对象，Math.sqrt 开方。"},
{"id": "j-22", "lang": "java", "level": "intermediate",
     "title": "继承与多态", "desc": "Animal 基类（name 字段、speak 返回 \"...\"），Dog 和 Cat 继承并重写 speak。\n遍历 Animal[] 数组输出 名字:叫声。",
     "expected": "Rex: Woof\nTom: Meow",
     "explain": "extends 继承，@Override 重写方法，父类引用指向子类对象。"},
{"id": "j-23", "lang": "java", "level": "intermediate",
     "title": "接口 interface", "desc": "定义 Shape 接口（double area()）。Circle（半径 2）与 Rectangle（3x4）实现它。输出两个面积（截断整数）。",
     "expected": "12\n12",
     "explain": "接口声明抽象方法，implements 实现；面积：πr²≈12.57→12、3*4=12。"},
{"id": "j-24", "lang": "java", "level": "intermediate",
     "title": "异常处理", "desc": "int[] a = {1,2,3}; 访问 a[5]，用 try-catch 捕获 ArrayIndexOutOfBoundsException 并输出 Error。",
     "expected": "Error",
     "explain": "try 内抛出异常，catch 捕获对应类型；可加 finally。"},
{"id": "j-25", "lang": "java", "level": "intermediate",
     "title": "ArrayList 集合", "desc": "创建 ArrayList<String>，添加 apple、banana、apple；删除第一个 apple；输出集合内容和大小。",
     "expected": "[banana, apple]\n2",
     "explain": "ArrayList 动态数组；remove(Object) 删除首个匹配元素。"},
{"id": "j-26", "lang": "java", "level": "intermediate",
     "title": "抽象类", "desc": "抽象类 Shape（抽象 area()，普通方法 info()），Square 实现。输出 area 与 info。",
     "expected": "16.0\nshape",
     "explain": "abstract 类可有抽象方法与具体方法。"},
{"id": "j-27", "lang": "java", "level": "intermediate",
     "title": "包装类 Integer", "desc": "输出 Integer 42、parseInt(\"123\")、max(10,20)、toBinaryString(5)。",
     "expected": "42\n123\n20\n101",
     "explain": "包装类提供静态工具方法；自动装箱拆箱。"},
{"id": "j-28", "lang": "java", "level": "intermediate",
     "title": "LinkedList", "desc": "链表添加 1，addFirst(0)，addLast(2)。输出链表、removeFirst()、删除后链表。",
     "expected": "[0, 1, 2]\n0\n[1, 2]",
     "explain": "LinkedList 支持头尾快速插入删除。"},
{"id": "j-29", "lang": "java", "level": "intermediate",
     "title": "TreeMap 有序映射", "desc": "放入 banana/apple/cherry 三个键。输出整个 TreeMap 与 firstKey()。",
     "expected": "{apple=5, banana=2, cherry=3}\napple",
     "explain": "TreeMap 按键自然顺序自动排序。"},
{"id": "j-30", "lang": "java", "level": "intermediate",
     "title": "super 调用父类", "desc": "Dog 继承 Animal：构造器 super(n) 传名，speak 重写并调用 super.speak()。输出名字与叫声。",
     "expected": "Rex\n... Woof",
     "explain": "super 调用父类构造器与方法。"},
{"id": "j-31", "lang": "java", "level": "advanced",
     "title": "HashMap 统计", "desc": "统计 s = \"abracadabra\" 中每个字符出现次数，按字符升序输出 字符:次数。",
     "expected": "a:5\nb:2\nc:1\nd:1\nr:2",
     "explain": "HashMap 键值对；getOrDefault 计数；TreeMap 或排序保证顺序。"},
{"id": "j-32", "lang": "java", "level": "advanced",
     "title": "HashSet 去重", "desc": "List<Integer> {1,2,2,3,3,3} 放入 HashSet 去重，排序后输出（空格分隔）。",
     "expected": "1 2 3",
     "explain": "HashSet 自动去重且无序，用排序或 TreeSet 保证升序。"},
{"id": "j-33", "lang": "java", "level": "advanced",
     "title": "泛型", "desc": "定义泛型方法 maxOf(T a, T b, Comparator<T> cmp) 返回较大者。用它对 5 和 9 输出较大值；再用字符串 \"abc\" 与 \"abd\" 比较。",
     "expected": "9\nabd",
     "explain": "泛型方法 <T> 声明类型参数；Comparator 定义比较规则。"},
{"id": "j-34", "lang": "java", "level": "advanced",
     "title": "StringBuilder", "desc": "用 StringBuilder 循环拼接 1 到 5，输出结果和长度。",
     "expected": "12345\n5",
     "explain": "StringBuilder 可变字符串，append 高效拼接，toString 转回。"},
{"id": "j-35", "lang": "java", "level": "advanced",
     "title": "static 与 final", "desc": "Counter 类：static int count（类级），final String name（实例级）。创建 5 个对象（名字 C1..C5），输出最终 count。",
     "expected": "5",
     "explain": "static 成员属于类共享；final 字段只能赋值一次。"},
{"id": "j-36", "lang": "java", "level": "advanced",
     "title": "内部类与匿名类", "desc": "静态内部类 Helper 提供 triple(7)；匿名 Runnable 输出 run。依次输出。",
     "expected": "run\n21",
     "explain": "内部类组织相关类；匿名类实现接口。"},
{"id": "j-37", "lang": "java", "level": "advanced",
     "title": "泛型方法", "desc": "泛型方法 first(T[] arr) 返回首元素。对 Integer[] 与 String[] 调用并输出。",
     "expected": "10\na",
     "explain": "<T> 声明泛型方法，调用时推导类型。"},
{"id": "j-38", "lang": "java", "level": "advanced",
     "title": "Optional 类", "desc": "find(true) 返回 Optional.of(\"value\")，find(false) 返回空。输出 orElse 结果和 map 大写结果。",
     "expected": "value\nnone\nVALUE",
     "explain": "Optional 显式处理空值，避免 NullPointerException。"},
{"id": "j-39", "lang": "java", "level": "advanced",
     "title": "try-with-resources", "desc": "Resource 实现 AutoCloseable，构造打印 open、close 打印 close。try 中使用后输出顺序。",
     "expected": "open file\nusing\nclose file",
     "explain": "try-with-resources 自动调用 close()。"},
{"id": "j-40", "lang": "java", "level": "advanced",
     "title": "LocalDate 日期", "desc": "LocalDate.of(2024,2,29)。输出 +1 天、星期几、是否闰年。",
     "expected": "2024-03-01\nTHURSDAY\ntrue",
     "explain": "LocalDate 不可变日期；2024 是闰年。"},
{"id": "j-41", "lang": "java", "level": "expert",
     "title": "Stream API", "desc": "List<Integer> {1,2,3,4,5,6,7,8,9,10}。用 stream 过滤偶数、每个乘以 10、求和并输出。",
     "expected": "300",
     "explain": "filter/map/reduce 流水线；2+4+6+8+10=30，×10=300。"},
{"id": "j-42", "lang": "java", "level": "expert",
     "title": "Lambda 表达式", "desc": "List<String> {\"pear\",\"apple\",\"kiwi\"} 用 Lambda 实现 Comparator 按长度排序，输出排序后的列表。",
     "expected": "[pear, kiwi, apple]",
     "explain": "Lambda (a,b) -> a.length()-b.length() 作为函数式接口实例。"},
{"id": "j-43", "lang": "java", "level": "expert",
     "title": "多线程", "desc": "创建 5 个线程，各自往共享 List 中添加 i*i（i=1..5）。用 volatile/同步保证安全，join 后排序输出。",
     "expected": "[1, 4, 9, 16, 25]",
     "explain": "Thread/Runnable 创建线程，synchronized 同步共享数据。"},
{"id": "j-44", "lang": "java", "level": "expert",
     "title": "Comparator 排序", "desc": "Student 类（name、score）。数组含 3 名学生，用 Comparator 按 score 降序排序，输出第一名 名字 分数。",
     "expected": "Bob 92",
     "explain": "Comparator.comparingInt(...).reversed() 链式定义排序规则。"},
{"id": "j-45", "lang": "java", "level": "expert",
     "title": "枚举 enum", "desc": "定义枚举 Day {MONDAY, TUESDAY, WEDNESDAY}。遍历输出全部枚举值；再用 valueOf(\"TUESDAY\") 判断是否等于枚举第 2 个值。",
     "expected": "MONDAY TUESDAY WEDNESDAY\ntrue",
     "explain": "enum 自带 values() 与 valueOf()；枚举值按定义顺序编号。"},
{"id": "j-46", "lang": "java", "level": "expert",
     "title": "AtomicInteger 原子类", "desc": "初值 10：incrementAndGet、addAndGet(5) 后输出；再输出 compareAndSet(16,100) 与新值。",
     "expected": "16\ntrue\n100",
     "explain": "原子类保证线程安全的整数操作。"},
{"id": "j-47", "lang": "java", "level": "expert",
     "title": "CompletableFuture 异步", "desc": "supplyAsync(() -> 21) 然后 thenApply(x -> x*2)，get() 输出结果。",
     "expected": "42",
     "explain": "CompletableFuture 异步任务链式组合。"},
{"id": "j-48", "lang": "java", "level": "expert",
     "title": "反射 Reflection", "desc": "对 Person 类：输出字段 name 的名字、读取 age 字段值、调用 greet() 方法。",
     "expected": "name\n25\nhi",
     "explain": "反射在运行时检查类结构并动态调用。"},
{"id": "j-49", "lang": "java", "level": "expert",
     "title": "注解 Annotation", "desc": "定义 @Info(\"test\") 注解（RUNTIME 保留），标注在类上，运行时读取 value 输出。",
     "expected": "test",
     "explain": "注解携带元数据，可经反射读取。"},
{"id": "j-50", "lang": "java", "level": "expert",
     "title": "单例模式", "desc": "实现懒加载单例 Singleton（私有构造、getInstance）。获取两次输出是否同一对象。",
     "expected": "true",
     "explain": "单例保证全局只有一个实例，私有构造阻止 new。"},
{"id": "py-01", "lang": "python", "level": "beginner",
     "title": "Hello, World!", "desc": "使用 print() 输出字符串：Hello, World!",
     "expected": "Hello, World!", "explain": "print() 在标准输出打印内容。"},
{"id": "py-02", "lang": "python", "level": "beginner",
     "title": "变量与算术运算", "desc": "从一行输入读取两个整数（空格分隔），输出它们的和。\n输入示例：12 30",
     "stdin": "12 30", "expected": "42",
     "explain": "input().split() 分割字符串，int() 转换类型。"},
{"id": "py-03", "lang": "python", "level": "beginner",
     "title": "if / elif / else 条件判断", "desc": "读取一个分数（整数）。90 分及以上输出 A，60 分及以上输出 B，否则输出 C。\n输入示例：85",
     "stdin": "85", "expected": "B",
     "explain": "条件语句按顺序判断，满足第一个条件即执行。"},
{"id": "py-04", "lang": "python", "level": "beginner",
     "title": "for 循环与 range()", "desc": "读取整数 n，输出 1 到 n 的和。\n输入示例：100",
     "stdin": "100", "expected": "5050",
     "explain": "range(1, n+1) 生成 1..n 序列，sum() 求和。"},
{"id": "py-05", "lang": "python", "level": "beginner",
     "title": "while 循环", "desc": "用 while 循环输出：5 4 3 2 1（空格分隔，末尾换行）。",
     "expected": "5 4 3 2 1",
     "explain": "while 条件循环，注意更新计数器避免死循环。"},
{"id": "py-06", "lang": "python", "level": "beginner",
     "title": "print 的 sep 与 end", "desc": "用 print(1,2,3,sep='-') 输出一行；再用 end='|' 输出 a，然后输出 b（同一行）。",
     "expected": "1-2-3\na|b",
     "explain": "sep 指定分隔符，end 指定结尾字符。"},
{"id": "py-07", "lang": "python", "level": "beginner",
     "title": "字符串拼接与重复", "desc": "s1='Hello'，s2='World'。输出 s1 与 s2 用空格连接的结果，再输出 'ha' 重复 3 次。",
     "expected": "Hello World\nhahaha",
     "explain": "+ 拼接字符串，* 重复字符串。"},
{"id": "py-08", "lang": "python", "level": "beginner",
     "title": "逻辑运算符", "desc": "a=5, b=10, c=0。依次输出：a>0 且 b>0；a>10 或 c>0；not c。",
     "expected": "True\nFalse\nTrue",
     "explain": "and/or/not 是逻辑运算符，0 为假非 0 为真。"},
{"id": "py-09", "lang": "python", "level": "beginner",
     "title": "整除、取模与幂", "desc": "依次输出 17//5、17%5、2**10 的结果。",
     "expected": "3\n2\n1024",
     "explain": "// 整除，% 取余，** 幂运算。"},
{"id": "py-10", "lang": "python", "level": "beginner",
     "title": "类型转换", "desc": "s='123'。转为 int 输出 s+1；转为 float 输出 +0.5；str(n)+'!'。",
     "expected": "124\n123.5\n123!",
     "explain": "int()/float()/str() 在不同类型间转换。"},
{"id": "py-11", "lang": "python", "level": "elementary",
     "title": "列表操作", "desc": "列表 lst = [3, 1, 4, 1, 5]。依次：\n1) 排序后输出\n2) 追加 99 后输出\n3) 反转后输出",
     "expected": "[1, 1, 3, 4, 5]\n[1, 1, 3, 4, 5, 99]\n[99, 5, 4, 3, 1, 1]",
     "explain": "list.sort() 原地排序，append() 追加，reverse() 反转。"},
{"id": "py-12", "lang": "python", "level": "elementary",
     "title": "字符串方法", "desc": "s = 'hello world python'。依次输出：\n1) 用空格分割后以 '-' 连接\n2) 转大写\n3) 字符串长度",
     "expected": "hello-world-python\nHELLO WORLD PYTHON\n18",
     "explain": "split() 分割、join() 连接、upper() 大写、len() 长度。"},
{"id": "py-13", "lang": "python", "level": "elementary",
     "title": "字典统计字符", "desc": "统计 s = 'abracadabra' 中每个字符出现的次数，按字符升序输出 字符:次数，每行一个。",
     "expected": "a:5\nb:2\nc:1\nd:1\nr:2",
     "explain": "dict.get(k, 0) + 1 计数，sorted() 按键排序。"},
{"id": "py-14", "lang": "python", "level": "elementary",
     "title": "函数与参数", "desc": "定义函数 add(a, b=10) 返回 a+b。依次输出：\n1) add(5)\n2) add(5, 3)\n3) add(b=1, a=2)",
     "expected": "15\n8\n3",
     "explain": "默认参数 b=10，关键字参数可乱序传递。"},
{"id": "py-15", "lang": "python", "level": "elementary",
     "title": "元组解包与集合去重", "desc": "t = (1, 2, 3)，解包到 a, b, c 后输出 a+b+c。再对列表 [1, 2, 2, 3, 3, 3] 去重（用 set），排序后输出。",
     "expected": "6\n1 2 3",
     "explain": "a, b, c = t 元组解包；set() 去重，sorted() 排序。"},
{"id": "py-16", "lang": "python", "level": "elementary",
     "title": "字符串切片", "desc": "s='abcdefgh'。依次输出 s[2:5]、s[-3:]、s[::2]。",
     "expected": "cde\nfgh\naceg",
     "explain": "切片 [开始:结束:步长]，负索引从尾部数。"},
{"id": "py-17", "lang": "python", "level": "elementary",
     "title": "列表索引与负索引", "desc": "lst=[10,20,30,40]。输出 lst[0] 与 lst[-1]；输出 lst[1:3]；输出反转列表。",
     "expected": "10 40\n[20, 30]\n[40, 30, 20, 10]",
     "explain": "负索引访问尾部；[::-1] 反转列表。"},
{"id": "py-18", "lang": "python", "level": "elementary",
     "title": "enumerate 遍历", "desc": "fruits=['apple','banana','cherry']。用 enumerate(fruits, start=1) 输出 序号 水果。",
     "expected": "1 apple\n2 banana\n3 cherry",
     "explain": "enumerate 同时给出索引与元素，start 指定起始值。"},
{"id": "py-19", "lang": "python", "level": "elementary",
     "title": "字典 update 与 items", "desc": "d={'a':1}，用 update 添加 b=2、c=3，然后用 items() 遍历输出。",
     "expected": "a 1\nb 2\nc 3",
     "explain": "update 批量添加，items() 遍历键值对。"},
{"id": "py-20", "lang": "python", "level": "elementary",
     "title": "循环 else 与 break", "desc": "用 for+else 找出 2~9 之间的素数（素数 = 内层循环未 break），空格分隔输出。",
     "expected": "2 3 5 7",
     "explain": "循环没有 break 时执行 else 分支。"},
{"id": "py-21", "lang": "python", "level": "intermediate",
     "title": "列表推导式", "desc": "用列表推导式生成 0 到 9 中偶数的平方，空格分隔输出。",
     "expected": "0 4 16 36 64",
     "explain": "[x**2 for x in range(10) if x % 2 == 0] 推导式带过滤条件。"},
{"id": "py-22", "lang": "python", "level": "intermediate",
     "title": "lambda 与高阶函数", "desc": "nums = [3, -1, 2, -4, 5, -6]。依次输出：\n1) 用 filter+lambda 选出偶数\n2) 用 sorted+lambda 按绝对值排序",
     "expected": "[2, -4, -6]\n[-1, 2, 3, -4, 5, -6]",
     "explain": "filter 按条件过滤；sorted 的 key 参数指定排序依据。"},
{"id": "py-23", "lang": "python", "level": "intermediate",
     "title": "异常处理 try / except", "desc": "读取一行，尝试转为整数并输出其两倍；若转换失败输出 Bad Input。\n输入示例：abc",
     "stdin": "abc", "expected": "Bad Input",
     "explain": "try/except 捕获 ValueError；可加 else/finally。"},
{"id": "py-24", "lang": "python", "level": "intermediate",
     "title": "生成器 yield", "desc": "用生成器输出斐波那契数列前 10 项（从 0 开始），空格分隔。",
     "expected": "0 1 1 2 3 5 8 13 21 34",
     "explain": "含 yield 的函数是生成器，逐次惰性求值。"},
{"id": "py-25", "lang": "python", "level": "intermediate",
     "title": "文件读写 with open", "desc": "用 tempfile 创建临时文件，写入两行文本，然后用 with open 读取并输出第二行内容。",
     "expected": "line2",
     "explain": "with 语句自动管理文件关闭；tempfile.mkstemp 创建唯一临时文件。"},
{"id": "py-26", "lang": "python", "level": "intermediate",
     "title": "装饰器", "desc": "定义装饰器 shout，使被装饰函数的返回值变为大写。装饰 greet(name)，输出 greet('world') 的结果。",
     "expected": "HELLO WORLD",
     "explain": "装饰器是接收函数返回新函数的语法糖：@shout 等价于 greet = shout(greet)。"},
{"id": "py-27", "lang": "python", "level": "intermediate",
     "title": "嵌套函数与闭包", "desc": "make_multiplier(factor) 返回内部函数，内部函数返回 x*factor。创建 double 与 triple，输出 double(5) 和 triple(5)。",
     "expected": "10 15",
     "explain": "闭包捕获外层变量 factor，返回函数保留其引用。"},
{"id": "py-28", "lang": "python", "level": "intermediate",
     "title": "sorted 与 key 参数", "desc": "words=['banana','apple','cherry','date']。按长度排序输出；再按最后一个字符排序输出。",
     "expected": "['date', 'apple', 'banana', 'cherry']\n['banana', 'apple', 'date', 'cherry']",
     "explain": "sorted 的 key 指定排序依据；可配合 lambda。"},
{"id": "py-29", "lang": "python", "level": "intermediate",
     "title": "推导式进阶", "desc": "用字典推导式生成 1~4 的平方映射；用集合推导式生成 0~9 的偶数集合并排序输出。",
     "expected": "{1: 1, 2: 4, 3: 9, 4: 16}\n[0, 2, 4, 6, 8]",
     "explain": "字典推导式 {k: v for ...}，集合推导式 {x for ... if ...}。"},
{"id": "py-30", "lang": "python", "level": "intermediate",
     "title": "zip 并行迭代", "desc": "names=['Alice','Bob'] 与 scores=[90,85] 用 zip 遍历输出。再 zip((1,2),(3,4)) 解包输出。",
     "expected": "Alice 90\nBob 85\n(1, 3) (2, 4)",
     "explain": "zip 按最短长度配对；结果可解包。"},
{"id": "py-31", "lang": "python", "level": "intermediate",
     "title": "自定义异常", "desc": "定义 NegativeError(Exception)。check(n) 在 n<0 时 raise 它。捕获后输出异常信息，再输出 check(5)。",
     "expected": "negative!\n10",
     "explain": "自定义异常继承 Exception；raise 主动抛出，except 捕获。"},
{"id": "py-32", "lang": "python", "level": "advanced",
     "title": "类与对象", "desc": "定义 Point 类（__init__ 存储 x, y；dist 计算到另一点的距离；__str__ 返回 (x,y)）。\n输出 p1=(0,0) 的字符串表示，以及 p1 到 p2=(3,4) 的距离（取整）。",
     "expected": "(0,0)\n5",
     "explain": "__init__ 构造、__str__ 字符串表示、实例方法通过 self 访问属性。"},
{"id": "py-33", "lang": "python", "level": "advanced",
     "title": "继承与多态", "desc": "Animal 基类（name 属性、speak 返回 '...'）。Dog 和 Cat 继承并重写 speak。\n依次输出 Rex 和 Tom 的 名字:叫声，用列表存储两种动物。",
     "expected": "Rex: Woof\nTom: Meow",
     "explain": "子类重写父类方法实现多态；super() 可调用父类方法。"},
{"id": "py-34", "lang": "python", "level": "advanced",
     "title": "多线程 threading", "desc": "创建 5 个线程，各自计算 i*i（i=1..5），用锁保护结果列表，主线程 join 后输出排序结果列表。",
     "expected": "[1, 4, 9, 16, 25]",
     "explain": "threading.Thread 启动线程，Lock 保证共享数据安全，join 等待完成。"},
{"id": "py-35", "lang": "python", "level": "advanced",
     "title": "异步编程 asyncio", "desc": "定义两个协程 task('A', 0.2) 和 task('B', 0.1)，各自 await asyncio.sleep 后返回 'X done'。用 asyncio.gather 并发运行，输出结果（空格分隔）。",
     "expected": "A done B done",
     "explain": "async def 定义协程，await 挂起，gather 并发调度，asyncio.run 启动事件循环。"},
{"id": "py-36", "lang": "python", "level": "advanced",
     "title": "上下文管理器", "desc": "实现 Greeter 类：__enter__ 打印 enter 并返回 self，__exit__ 打印 exit。用 with 执行并输出三行：enter、inside、exit。",
     "expected": "enter\ninside\nexit",
     "explain": "__enter__/__exit__ 协议使对象可用于 with；退出时自动调用 __exit__。"},
{"id": "py-37", "lang": "python", "level": "advanced",
     "title": "classmethod 与 staticmethod", "desc": "Counter 类：类属性 count，__init__ 时自增。@classmethod get_count 返回计数，@staticmethod double 返回两倍。创建两个实例后输出。",
     "expected": "2\n42",
     "explain": "@classmethod 接收 cls，@staticmethod 不接收特殊参数。"},
{"id": "py-38", "lang": "python", "level": "advanced",
     "title": "多重继承", "desc": "class A 和 B 都有 who() 返回 'A'/'B'。C(A,B) 继承。输出 c.who() 与 C.__mro__[0].__name__。",
     "expected": "A\nC",
     "explain": "多重继承按 MRO 从左到右查找方法。"},
{"id": "py-39", "lang": "python", "level": "advanced",
     "title": "运算符重载", "desc": "Point 类重载 __add__、__eq__、__str__。p1+p2 输出字符串；比较相等输出布尔。",
     "expected": "(4,6)\nTrue\nFalse",
     "explain": "__add__ 定义 +、__eq__ 定义 ==、__str__ 定义打印。"},
{"id": "py-40", "lang": "python", "level": "advanced",
     "title": "多进程 multiprocessing", "desc": "用 Pool(2) 对 [1,2,3,4] 并行应用 square，输出结果列表。",
     "expected": "[1, 4, 9, 16]",
     "explain": "Pool.map 在多进程中分发任务并收集结果。"},
{"id": "py-41", "lang": "python", "level": "advanced",
     "title": "property 属性", "desc": "Circle 类：私有 _r，property area 返回 3.14*r*r，radius 可读写。创建 r=1 输出 int(area)，改为 2 再输出。",
     "expected": "3\n12",
     "explain": "@property 将方法变为属性访问，setter 控制赋值。"},
{"id": "py-42", "lang": "python", "level": "expert",
     "title": "functools.reduce 函数式编程", "desc": "用 reduce 和 lambda 计算 [1, 2, 3, 4, 5] 所有元素的乘积，输出结果。",
     "expected": "120",
     "explain": "reduce(f, seq) 从左到右累积应用二元函数；1*2*3*4*5=120。"},
{"id": "py-43", "lang": "python", "level": "expert",
     "title": "正则表达式 re", "desc": "text = '订单号: A123-45, 编号: B678'。依次输出：\n1) findall 匹配形如 大写字母+3数字+'-'+2数字 的模式\n2) 用正则把 text 中所有数字替换为 #",
     "expected": "['A123-45']\n订单号: A###-##, 编号: B###",
     "explain": "re.findall 提取所有匹配；re.sub 按模式替换。"},
{"id": "py-44", "lang": "python", "level": "expert",
     "title": "dataclass 与类型注解", "desc": "用 @dataclass 定义 User 类：name: str、age: int、email: str = 'none'。\n创建 u = User('Alice', 25)，输出 repr 和三个字段。",
     "expected": "User(name='Alice', age=25, email='none')\nAlice 25 none",
     "explain": "dataclass 自动生成 __init__/__repr__；类型注解用于静态检查。"},
{"id": "py-45", "lang": "python", "level": "expert",
     "title": "生成器 send 与进阶用法", "desc": "定义生成器：初始 x=0，每次 yield 当前 x；若收到 send 的值则把 x 设为该值，否则 x+1。\n依次输出 next 两次的值、send(100) 的值、再 next 的值（分两行打印）。",
     "expected": "0 1\n100 101",
     "explain": "send() 向暂停的生成器传值；next(g) 等价 g.send(None)。"},
{"id": "py-46", "lang": "python", "level": "expert",
     "title": "lru_cache 记忆化", "desc": "用 @lru_cache 装饰递归斐波那契。先算 fib(10)，再调用 fib(10) 输出，最后输出 cache_info()。",
     "expected": "55\nCacheInfo(hits=9, misses=11, maxsize=None, currsize=11)",
     "explain": "lru_cache 缓存函数结果，第二次调用命中缓存。"},
{"id": "py-47", "lang": "python", "level": "expert",
     "title": "元类 metaclass", "desc": "定义 Meta(type)，在 __new__ 中给类字典注入 version=1.0。class Foo(metaclass=Meta) 后输出 Foo.version。",
     "expected": "1.0",
     "explain": "元类拦截类创建过程，可在 __new__ 中修改类属性。"},
{"id": "py-48", "lang": "python", "level": "expert",
     "title": "yield from 委托生成", "desc": "sub() 依次 yield 1,2；main() 用 yield from sub() 再 yield 3。输出 list(main())。",
     "expected": "[1, 2, 3]",
     "explain": "yield from 把子生成器的产出委托给外层迭代。"},
{"id": "py-49", "lang": "python", "level": "expert",
     "title": "functools.partial 偏函数", "desc": "power(base, exp) 返回 base**exp。用 partial 固定 exp=2 得 square、exp=3 得 cube。输出 square(5) 与 cube(2)。",
     "expected": "25 8",
     "explain": "partial 预绑定部分参数，生成新函数。"},
{"id": "py-50", "lang": "python", "level": "expert",
     "title": "contextlib 与装饰器链", "desc": "用 @contextmanager 定义 tag 上下文（进入打印 <name>，退出打印 </name>）。装饰器 deco 打印 start/end。组合输出。",
     "expected": "<p>\nstart\nhi\nend\n</p>",
     "explain": "contextmanager 用 yield 分隔进入/退出代码；装饰器链层层包裹。"},
{"id": "r-01", "lang": "rust", "level": "beginner",
     "title": "println! 输出", "desc": "使用 println! 输出：Hello, World!",
     "expected": "Hello, World!", "explain": "println! 宏带换行输出；fn main() 是程序入口。"},
{"id": "r-02", "lang": "rust", "level": "beginner",
     "title": "变量与可变性", "desc": "声明可变变量 n = 10，加 5 后输出结果。（提示：变量默认不可变，需要 mut）",
     "expected": "15",
     "explain": "let mut 声明可变变量，let 声明不可变；所有变量默认不可变是 Rust 特色。"},
{"id": "r-03", "lang": "rust", "level": "beginner",
     "title": "if-else 表达式", "desc": "score = 85。90 及以上输出 A，60 及以上输出 B，否则输出 C。",
     "expected": "B",
     "explain": "if 是表达式可返回值；注意条件两侧空格风格。"},
{"id": "r-04", "lang": "rust", "level": "beginner",
     "title": "for 循环与范围", "desc": "用 for 计算 1 到 10 的和（含 10），输出结果。",
     "expected": "55",
     "explain": "(1..=10) 含右端点，(1..10) 不含；for i in range 迭代。"},
{"id": "r-05", "lang": "rust", "level": "beginner",
     "title": "while 与 loop", "desc": "用 while 倒序输出：3 2 1（空格分隔）。",
     "expected": "3 2 1",
     "explain": "while 条件为真时循环；Rust 还有无限循环 loop。"},
{"id": "r-06", "lang": "rust", "level": "beginner",
     "title": "基本类型", "desc": "i32=42、f64=3.14、bool=true、char='A'。输出 42 A 3.14 true，再把 42 转 f64 除以 2 输出。",
     "expected": "42 A 3.14 true\n21",
     "explain": "as 关键字做类型转换；{} 格式化。"},
{"id": "r-07", "lang": "rust", "level": "beginner",
     "title": "逻辑运算符", "desc": "a=5。输出 a>0 && a<10、a>10 || a==5、!(a==5)。",
     "expected": "true\ntrue\nfalse",
     "explain": "&&、||、! 逻辑运算。"},
{"id": "r-08", "lang": "rust", "level": "beginner",
     "title": "loop 与 break 返回值", "desc": "loop 中 n 从 1 递增，当 n*n>30 时 break n。输出该 n 与其平方。",
     "expected": "6\n36",
     "explain": "loop 无限循环，break 后可带返回值。"},
{"id": "r-09", "lang": "rust", "level": "beginner",
     "title": "范围与 rev()", "desc": "用 (1..=5).rev() 收集到 Vec 并输出（空格分隔）。",
     "expected": "5 4 3 2 1",
     "explain": "rev() 反转迭代方向。"},
{"id": "r-10", "lang": "rust", "level": "beginner",
     "title": "char 与 ASCII", "desc": "c='B'。输出 c as u8、下一个字符、c.is_uppercase()。",
     "expected": "66 C\ntrue",
     "explain": "char 可转 u8 取 ASCII；is_uppercase 判断。"},
{"id": "r-11", "lang": "rust", "level": "elementary",
     "title": "函数与返回值", "desc": "定义 add(x: i32, y: i32) -> i32 返回 x+y，输出 add(20, 22) 的结果。",
     "expected": "42",
     "explain": "fn 定义函数，-> 声明返回类型，最后一个表达式即返回值。"},
{"id": "r-12", "lang": "rust", "level": "elementary",
     "title": "String 与 &str", "desc": "let mut s = String::from(\"hello\"); push_str(\" world\")。输出：内容 和 长度（空格分隔）。",
     "expected": "hello world 11",
     "explain": "String 可增长的堆字符串；len() 返回字节数。"},
{"id": "r-13", "lang": "rust", "level": "elementary",
     "title": "Vec 动态数组", "desc": "创建空 Vec<i32>，依次 push 1..5，输出第 3 个元素、总长度、以及所有元素（空格分隔）。",
     "expected": "3\n5\n1 2 3 4 5",
     "explain": "Vec::new() + push 追加；vec![...] 宏初始化；下标访问。"},
{"id": "r-14", "lang": "rust", "level": "elementary",
     "title": "元组与解构", "desc": "let t = (10, 20.5, \"hi\"); 解构出三个值，输出 10 20.5 hi（空格分隔）。",
     "expected": "10 20.5 hi",
     "explain": "元组固定长度异质元素；(a, b, c) = t 模式解构。"},
{"id": "r-15", "lang": "rust", "level": "elementary",
     "title": "match 模式匹配", "desc": "let n = 2; 用 match 把 1..=3 映射为 Monday/Tuesday/Wednesday，其他为 Other，输出 n 对应的值。",
     "expected": "Tuesday",
     "explain": "match 穷尽所有分支；..= 范围模式。"},
{"id": "r-16", "lang": "rust", "level": "elementary",
     "title": "数组", "desc": "[i32;5] 初始化 {1,2,3,4,5}：输出 len 与第一个元素；再用 [7;3] 输出三元素数组。",
     "expected": "5 1\n[7, 7, 7]",
     "explain": "数组固定长度，[v; n] 重复填充。"},
{"id": "r-17", "lang": "rust", "level": "elementary",
     "title": "切片", "desc": "数组取 [1..4] 切片输出；字符串取前 5 字符输出并输出字符串字节长度。",
     "expected": "[20, 30, 40]\nhello 11",
     "explain": "切片是数组/字符串的视图，&arr[a..b]。"},
{"id": "r-18", "lang": "rust", "level": "elementary",
     "title": "chars() 遍历字符", "desc": "s=\"hello\"：用 chars() 逐个打印（不换行）再换行，输出字符个数。",
     "expected": "hello\n5",
     "explain": "chars() 迭代 Unicode 字符。"},
{"id": "r-19", "lang": "rust", "level": "elementary",
     "title": "Vec 排序与去重", "desc": "v={3,1,4,1,5}：sort 后输出，dedup 后再输出。",
     "expected": "1 1 3 4 5\n1 3 4 5",
     "explain": "sort 升序排序，dedup 移除相邻重复。"},
{"id": "r-20", "lang": "rust", "level": "elementary",
     "title": "模式解构", "desc": "结构体 Point{x,y} 解构输出 x y；元组 (1,2) 解构输出。",
     "expected": "3 4\n1 2",
     "explain": "let 模式可解构结构体与元组。"},
{"id": "r-21", "lang": "rust", "level": "intermediate",
     "title": "所有权与借用", "desc": "写函数 calc_len(s: &String) -> usize 返回字符串长度。创建 s，借用求长度后仍能使用 s，输出 s 与长度。",
     "expected": "rust 4",
     "explain": "& 借用不转移所有权；借用期间原变量仍可用。"},
{"id": "r-22", "lang": "rust", "level": "intermediate",
     "title": "结构体与 impl", "desc": "定义 Point { x, y } 和 impl 方法 dist(&self, other) -> f64。输出 (0,0) 到 (3,4) 距离取整。",
     "expected": "5",
     "explain": "struct 定义数据，impl 定义方法；self 引用实例。"},
{"id": "r-23", "lang": "rust", "level": "intermediate",
     "title": "枚举 enum 与数据", "desc": "定义枚举 Message { Text(String), Num(i32) }。创建两个实例，用 match 分别提取数据输出。",
     "expected": "hi\n42",
     "explain": "枚举成员可携带数据，match 模式解构提取。"},
{"id": "r-24", "lang": "rust", "level": "intermediate",
     "title": "Option 类型", "desc": "函数 find(a: &[i32], t: i32) -> Option<usize> 返回下标。输出 find(&[1,2,3], 2) 用 unwrap() 的值，和 find(&[1,2,3], 9) 用 unwrap_or(99) 的值。",
     "expected": "1\n99",
     "explain": "Option 表示可能为空；unwrap 取 Some 值，unwrap_or 提供默认值。"},
{"id": "r-25", "lang": "rust", "level": "intermediate",
     "title": "HashMap 统计", "desc": "统计 \"abracadabra\" 每个字符出现次数，按字符顺序输出 字符:次数（每行一个）。",
     "expected": "a:5\nb:2\nc:1\nd:1\nr:2",
     "explain": "HashMap 键值对；entry API 或 get+insert 计数。"},
{"id": "r-26", "lang": "rust", "level": "intermediate",
     "title": "可变引用 &mut", "desc": "let mut n=10；创建 &mut 引用，*r += 5 后输出 n。",
     "expected": "15",
     "explain": "&mut 可修改被引用值，需先解引用。"},
{"id": "r-27", "lang": "rust", "level": "intermediate",
     "title": "关联函数与方法", "desc": "Point 结构体：关联函数 origin()（无 self），方法 len_sq(&self)。输出两者结果。",
     "expected": "0 25",
     "explain": "impl 内无 self 的是关联函数（:: 调用），有 self 的是方法。"},
{"id": "r-28", "lang": "rust", "level": "intermediate",
     "title": "Option 组合器", "desc": "Some(5) 与 None 分别 map(x*2) 后 unwrap_or(-1)；Some(5) 再 and_then(|x| Some(x+1)) 输出。",
     "expected": "10\n-1\n6",
     "explain": "map 变换值，unwrap_or 给默认值，and_then 链式。"},
{"id": "r-29", "lang": "rust", "level": "intermediate",
     "title": "Result 错误处理", "desc": "Ok(42) 用 unwrap_or(0)；Err(\"oops\") 用 map_err 包装后 unwrap_err 输出错误信息。",
     "expected": "42\nerr:oops",
     "explain": "Result<T,E> 表示可失败操作；map_err 转换错误类型。"},
{"id": "r-30", "lang": "rust", "level": "intermediate",
     "title": "match 匹配切片与守卫", "desc": "匹配 Vec 切片 [1, rest..] 输出；对元组 (10,20) 用守卫判断大小输出。",
     "expected": "starts 1, len 2\n10 20",
     "explain": "rest@.. 捕获剩余；if 守卫增加条件。"},
{"id": "r-31", "lang": "rust", "level": "advanced",
     "title": "泛型", "desc": "定义泛型函数 max_of<T: PartialOrd>(a: T, b: T) -> T 返回较大者。分别对整数 5,9 与字符串 \"abc\",\"abd\" 调用并输出。",
     "expected": "9\nabd",
     "explain": "<T> 泛型参数，T: PartialOrd 约束需要比较能力。"},
{"id": "r-32", "lang": "rust", "level": "advanced",
     "title": "trait 特性", "desc": "定义 trait Describable { fn describe(&self) -> String; }。为 Person {name, age} 实现它。创建实例输出描述。",
     "expected": "Alice (25)",
     "explain": "trait 定义共享行为，impl Trait for Type 实现。"},
{"id": "r-33", "lang": "rust", "level": "advanced",
     "title": "迭代器", "desc": "nums = vec![1,2,3,4,5,6]。用迭代器 filter 偶数、map 平方、collect 成 Vec，输出结果（调试格式）。",
     "expected": "[4, 16, 36]",
     "explain": "filter/map 惰性链式调用，collect 收集为集合；{:?} 调试输出。"},
{"id": "r-34", "lang": "rust", "level": "advanced",
     "title": "闭包", "desc": "factor = 3; 定义闭包 |x| x * factor 捕获环境。对 vec![1,2,3] 逐项调用输出结果（空格分隔）。",
     "expected": "3 6 9",
     "explain": "闭包可捕获外部变量；类型由推断确定，可传给 map 等。"},
{"id": "r-35", "lang": "rust", "level": "advanced",
     "title": "Result 错误处理", "desc": "函数 div(a: f64, b: f64) -> Result<f64, String>（除零返回 Err）。输出 div(10.0, 2.0).unwrap() 和 div(1.0, 0.0).unwrap_or(-1.0)。",
     "expected": "5\n-1",
     "explain": "Result<T,E> 表示成功/失败；unwrap_or 失败时给默认值。"},
{"id": "r-36", "lang": "rust", "level": "advanced",
     "title": "泛型结构体", "desc": "Pair<T> 存两个同型值，max() 返回较大者（T: PartialOrd）。对整数与 &str 调用输出。",
     "expected": "9\nz",
     "explain": "泛型结构体 + trait 约束 PartialOrd。"},
{"id": "r-37", "lang": "rust", "level": "advanced",
     "title": "trait 默认方法", "desc": "trait Greet 定义默认方法 greet()（调用 name()）。User 实现 name，derive(Debug)。输出 greet 与调试表示。",
     "expected": "Hello, user!\nUser { id: 7 }",
     "explain": "trait 可提供默认实现；#[derive(Debug)] 自动生成调试输出。"},
{"id": "r-38", "lang": "rust", "level": "advanced",
     "title": "enumerate 与 collect", "desc": "words={\"a\",\"b\",\"c\"}：enumerate 遍历输出 下标+单词；再用 enumerate().collect() 收集到 HashMap 输出 m[&1]。",
     "expected": "0a 1b 2c\nb",
     "explain": "enumerate 附加索引；迭代器可收集到 HashMap。"},
{"id": "r-39", "lang": "rust", "level": "advanced",
     "title": "闭包 move 捕获", "desc": "move 闭包拥有 Vec 后调用返回长度；普通闭包捕获 factor=2 计算 21*2。",
     "expected": "3\n42",
     "explain": "move 把捕获值所有权转移进闭包。"},
{"id": "r-40", "lang": "rust", "level": "advanced",
     "title": "? 错误传播", "desc": "parse_num(s) 用 ? 解析并乘 2，返回 Result。输出 Ok 与 Err 两种结果。",
     "expected": "Ok(42)\nErr(ParseIntError { kind: InvalidDigit })",
     "explain": "? 把错误提前返回，简化错误传播。"},
{"id": "r-41", "lang": "rust", "level": "expert",
     "title": "生命周期", "desc": "函数 longest<'a>(x: &'a str, y: &'a str) -> &'a str 返回较长者。对 \"abc\" 与 \"xy\" 调用并输出。",
     "expected": "abc",
     "explain": "'a 生命周期参数：返回值寿命取输入较短者，保证引用安全。"},
{"id": "r-42", "lang": "rust", "level": "expert",
     "title": "Box 与递归类型", "desc": "定义递归枚举 List<T> { Cons(T, Box<List<T>>), Nil }。构建 1 -> 2 -> 3 链表，写函数求长度并输出。",
     "expected": "3",
     "explain": "Box 把数据放堆上，打破无限大小使递归类型合法。"},
{"id": "r-43", "lang": "rust", "level": "expert",
     "title": "模式匹配进阶", "desc": "let n = 25; 用 match 带守卫：n 能被 7 整除输出 seven；能被 5 整除输出 five；其他输出 n 本身。",
     "expected": "five",
     "explain": "match 守卫 if 附加条件；25 被 5 整除。"},
{"id": "r-44", "lang": "rust", "level": "expert",
     "title": "模块系统", "desc": "定义 mod math { pub fn square(x: i32) -> i32 { x * x } }。通过 crate 路径调用，输出 square(12) 和 use 引入后调用 square(5)。",
     "expected": "144\n25",
     "explain": "mod 定义模块，pub 公开项，use 引入简化路径。"},
{"id": "r-45", "lang": "rust", "level": "expert",
     "title": "迭代器组合", "desc": "a = vec![1,2,3]; b = vec![4,5,6]。用 chain 连接后 filter_map：偶数值平方，奇数丢弃；输出收集结果。",
     "expected": "[4, 16, 36]",
     "explain": "chain 拼接两个迭代器，filter_map 同时过滤与映射。"},
{"id": "r-46", "lang": "rust", "level": "expert",
     "title": "Rc 与 RefCell", "desc": "Rc<RefCell<i32>> 初始 5，克隆引用后借可变加 3。输出值与强引用计数。",
     "expected": "8 2",
     "explain": "Rc 共享所有权，RefCell 提供运行时借用检查。"},
{"id": "r-47", "lang": "rust", "level": "expert",
     "title": "zip 与 flat_map", "desc": "两个 Vec 用 zip 逐对求和输出；单词列表用 flat_map 展平字符输出。",
     "expected": "[11, 22, 33]\n['a', 'b', 'c', 'd', 'e', 'f']",
     "explain": "zip 配对两个迭代器，flat_map 展平嵌套迭代。"},
{"id": "r-48", "lang": "rust", "level": "expert",
     "title": "宏定义 macro_rules", "desc": "定义 square! 宏（表达式平方）。输出 square!(5) 与 square!(3+2)。",
     "expected": "25\n25",
     "explain": "macro_rules! 声明式宏在编译期展开代码。"},
{"id": "r-49", "lang": "rust", "level": "expert",
     "title": "@ 模式绑定", "desc": "匹配 v.get(1)：Some(x@2) 输出 two:x，否则输出 other:x。",
     "expected": "two: 2",
     "explain": "@ 同时绑定值并匹配模式。"},
{"id": "r-50", "lang": "rust", "level": "expert",
     "title": "parse 字符串转换", "desc": "把 \"42\" parse 成 i32、\"3.14\" parse 成 f64、String 转 i64，分别输出。",
     "expected": "42\n3.14\n7",
     "explain": "FromStr trait 的 parse 推断目标类型。"},

    # ======================== 实战（开发真题） ========================
    {"id": "py-51", "lang": "python", "level": "practical",
     "title": "CSV 数据处理", "desc": "从 stdin 读取 3 行 CSV（姓名,分数），输出平均分（整除）和最高分学生姓名。\n输入示例：\nAlice,90\nBob,75\nCindy,87",
     "stdin": "Alice,90\nBob,75\nCindy,87", "expected": "84\nAlice",
     "explain": "split 解析 CSV 行，max 按分数取最高分学生。"},

    {"id": "py-52", "lang": "python", "level": "practical",
     "title": "日志解析与统计", "desc": "解析 stdin 日志（时间 级别 消息），统计 ERROR 行数，并按级别字母序输出 级别:次数。\n输入示例：\n2024-01-01 10:00:00 INFO 服务启动\n2024-01-01 10:00:01 ERROR 连接失败\n2024-01-01 10:00:02 ERROR 请求超时\n2024-01-01 10:00:03 INFO 重试成功",
     "stdin": "2024-01-01 10:00:00 INFO 服务启动\n2024-01-01 10:00:01 ERROR 连接失败\n2024-01-01 10:00:02 ERROR 请求超时\n2024-01-01 10:00:03 INFO 重试成功",
     "expected": "2\nERROR:2 INFO:2",
     "explain": "Counter 统计日志级别，ERROR 单独计数。"},

    {"id": "py-53", "lang": "python", "level": "practical",
     "title": "JSON 解析提取字段", "desc": "解析内置 JSON 字符串，依次输出 user.name、user.email 和 user.address.city。",
     "expected": "Alice\nalice@example.com\nShanghai",
     "explain": "json.loads 解析后按键取值，支持嵌套访问。"},

    {"id": "py-54", "lang": "python", "level": "practical",
     "title": "线程池并发计算", "desc": "用 ThreadPoolExecutor（4 线程）并发计算 1~10 的平方，汇总输出平方和。",
     "expected": "385",
     "explain": "ex.map 并发执行任务，sum 汇总结果。"},

    {"id": "py-55", "lang": "python", "level": "practical",
     "title": "文件读写与统计", "desc": "向 data.txt 写入两行文本，再读回统计行数和单词总数，输出\"行数 单词数\"。",
     "expected": "2 6",
     "explain": "open 写入/读取文件，split 统计每行单词数。"},

    {"id": "c-51", "lang": "c", "level": "practical",
     "title": "链表反转", "desc": "实现链表反转：依次在头插入 1~5，反转链表后从新头遍历输出（空格分隔）。",
     "expected": "1 2 3 4 5",
     "explain": "三指针迭代反转，cur->next 指向前驱。"},

    {"id": "c-52", "lang": "c", "level": "practical",
     "title": "单词频率统计", "desc": "统计句子 \"apple banana apple cherry banana apple\" 中每个单词出现次数，按次数降序输出（同次数按字母序），格式 单词:次数 空格分隔。",
     "expected": "apple:3 banana:2 cherry:1",
     "explain": "strtok 切分单词，结构体数组计数，qsort 排序。"},

    {"id": "c-53", "lang": "c", "level": "practical",
     "title": "文件逐行读取", "desc": "向 data.txt 写入 3 行文本，读回输出总行数和最长行的行号（空格分隔）。",
     "expected": "3 3",
     "explain": "fgets 逐行读取，strlen 计算长度并记录最长行号。"},

    {"id": "c-54", "lang": "c", "level": "practical",
     "title": "CSV 销售汇总", "desc": "写入 sales.csv（产品,销售额 3 行），读回统计总销售额和记录数，输出\"总额 条数\"。",
     "expected": "300 3",
     "explain": "strchr 定位逗号，atoi 转换金额累加。"},

    {"id": "c-55", "lang": "c", "level": "practical",
     "title": "求中位数", "desc": "对数组 {7,3,9,1,5,11,4} 升序排序后输出中间位置元素（中位数）。",
     "expected": "5",
     "explain": "qsort 排序后取下标 n/2 的元素。"},

    {"id": "j-51", "lang": "java", "level": "practical",
     "title": "单词计数统计", "desc": "统计数组 {\"bug\",\"fix\",\"bug\",\"deploy\",\"fix\",\"test\",\"bug\"} 中每个词出现次数，按字母序逐行输出 词:次数。",
     "expected": "bug:3\ndeploy:1\nfix:2\ntest:1",
     "explain": "TreeMap 自动排序，merge 方法累加计数。"},

    {"id": "j-52", "lang": "java", "level": "practical",
     "title": "文件读写", "desc": "向 data.txt 写入两行文本，读回统计行数与字符总数（不含换行），输出\"行数 字符数\"。",
     "expected": "2 31",
     "explain": "try-with-resources 自动关闭，BufferedReader 逐行统计。"},

    {"id": "j-53", "lang": "java", "level": "practical",
     "title": "线程池并行计算", "desc": "用固定 4 线程的 ExecutorService 并发计算 1~10 的平方，汇总输出平方和。",
     "expected": "385",
     "explain": "submit 提交任务返回 Future，get 汇总结果。"},

    {"id": "j-54", "lang": "java", "level": "practical",
     "title": "正则提取数字", "desc": "用正则从日志行 \"GET /api/users?id=42 200 12ms\" 中提取所有连续数字，逐行输出。",
     "expected": "42\n200\n12",
     "explain": "Pattern/Matcher 分组匹配 \\d+，find 循环提取。"},

    {"id": "j-55", "lang": "java", "level": "practical",
     "title": "Stream 实战", "desc": "对名字列表 [\"alice\",\"bob\",\"carol\",\"alice\",\"dave\"]：输出去重后数量；再用 Stream 过滤长度≥4、转大写、去重、排序后输出列表。",
     "expected": "4\n[ALICE, CAROL, DAVE]",
     "explain": "distinct/count/filter/map/sorted 链式管道处理。"},

    {"id": "r-51", "lang": "rust", "level": "practical",
     "title": "错误处理实战", "desc": "实现 parse_and_double：把字符串转 i32 并翻倍，失败返回错误；分别解析 \"21\" 和 \"abc\" 输出 Result 结果。",
     "expected": "Ok(42)\nErr(\"invalid: invalid digit found in string\")",
     "explain": "parse 结合 map_err 与 map 链式转换。"},

    {"id": "r-52", "lang": "rust", "level": "practical",
     "title": "文件读取统计", "desc": "向 data.txt 写入两行文本，读回统计行数与单词总数，输出\"行数 单词数\"。",
     "expected": "2 6",
     "explain": "fs::write 写入，read_to_string 读取后 lines 与 split_whitespace 统计。"},

    {"id": "r-53", "lang": "rust", "level": "practical",
     "title": "迭代器解析 CSV", "desc": "解析 CSV 字符串（产品,销售额 3 行），用迭代器链式处理，输出记录数与销售总额。",
     "expected": "3 300",
     "explain": "filter_map 跳过无效行，split(',') 解析字段。"},

    {"id": "r-54", "lang": "rust", "level": "practical",
     "title": "多线程并行求和", "desc": "将 1~10 分成两半，一个子线程计算后半部分和，主线程计算前半部分，汇总输出总和。",
     "expected": "55",
     "explain": "thread::spawn 移动所有权，join 获取结果。"},

    {"id": "r-55", "lang": "rust", "level": "practical",
     "title": "HTTP 方法统计", "desc": "统计数组 {\"get\",\"post\",\"get\",\"put\",\"get\",\"post\"} 出现次数，按次数降序（同次数按方法字母序）输出 方法:次数 空格分隔。",
     "expected": "get:3 post:2 put:1",
     "explain": "HashMap 计数后转 Vec 排序输出。"},

    {"id": "cpp-51", "lang": "cpp", "level": "practical",
     "title": "文件流读写", "desc": "向 data.txt 写入两行文本，读回统计行数与单词总数，输出\"行数 单词数\"。",
     "expected": "2 5",
     "explain": "ofstream/ifstream 配合 getline 逐行处理。"},

    {"id": "cpp-52", "lang": "cpp", "level": "practical",
     "title": "单词反转", "desc": "将句子 \"deploy fix test\" 按空格拆分，每个单词反转后按原顺序输出。",
     "expected": "yolped xif tset",
     "explain": "stringstream 拆分单词，rbegin/rend 反转。"},

    {"id": "cpp-53", "lang": "cpp", "level": "practical",
     "title": "日志级别统计", "desc": "统计日志级别数组 {\"warn\",\"info\",\"warn\",\"error\",\"info\",\"warn\"} 出现次数，按级别字母序逐行输出 级别:次数。",
     "expected": "error:1\ninfo:2\nwarn:3",
     "explain": "map 自动按键排序并计数。"},

    {"id": "cpp-54", "lang": "cpp", "level": "practical",
     "title": "多线程并行求和", "desc": "用两个 std::thread 分别计算 1~5 和 6~10 的和，join 后输出总和。",
     "expected": "55",
     "explain": "线程通过引用参数写回结果，join 等待完成。"},

    {"id": "cpp-55", "lang": "cpp", "level": "practical",
     "title": "智能指针共享", "desc": "用 shared_ptr 管理 Task 对象：创建后拷贝共享、输出引用计数，reset 一个指针后再输出计数，离开作用域自动析构。",
     "expected": "create 1\n2\n1\ndestroy 1\ndone",
     "explain": "make_shared 创建，use_count 查看计数，引用归零自动析构。"}
]


def find_question(qid):
    """按 id 查找题目，找不到返回 None。"""
    for q in QUESTIONS:
        if q["id"] == qid:
            return q
    return None
